# Generated by Django 2.1.3 on 2019-10-25 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='atuser',
            table='at_user',
        ),
    ]
