# Generated by Django 2.1.3 on 2019-11-06 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20191025_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atuser',
            name='u_password',
            field=models.CharField(max_length=256),
        ),
    ]
