# Generated by Django 2.1.3 on 2019-11-14 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20191106_1733'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productname', models.CharField(max_length=64)),
                ('productdesc', models.CharField(max_length=200)),
                ('producter', models.CharField(max_length=200)),
                ('create_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'at_product',
            },
        ),
    ]
