# Generated by Django 2.1.3 on 2019-11-15 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='create_time',
            new_name='p_create_time',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='productdesc',
            new_name='p_productdesc',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='producter',
            new_name='p_producter',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='productname',
            new_name='p_productname',
        ),
    ]
