# Generated by Django 2.1.3 on 2019-11-15 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20191115_1057'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='p_productdesc',
            new_name='p_product_desc',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='p_producter',
            new_name='p_product_er',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='p_productname',
            new_name='p_product_name',
        ),
    ]
