# Generated by Django 2.1.3 on 2019-11-21 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_apis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apis',
            name='api_method',
            field=models.BooleanField(choices=[(0, 'get'), (1, 'post')], default=0, max_length=200),
        ),
    ]
