# Generated by Django 2.1.3 on 2019-11-25 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20191121_1526'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apistep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_name', models.CharField(max_length=100)),
                ('api_step', models.CharField(max_length=200)),
                ('api_url', models.CharField(max_length=800)),
                ('api_param_value', models.CharField(max_length=800)),
                ('api_method', models.CharField(choices=[('0', 'get'), ('1', 'post')], default='get', max_length=200)),
                ('api_result', models.CharField(max_length=200)),
                ('api_status', models.BooleanField()),
                ('create_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'at_api_step',
            },
        ),
        migrations.CreateModel(
            name='Apitest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_t_name', models.CharField(max_length=64)),
                ('api_t_desc', models.CharField(max_length=200)),
                ('api_t_ter', models.CharField(max_length=16)),
                ('api_t_res', models.BooleanField()),
                ('create_time', models.DateTimeField(auto_now=True)),
                ('api_t_pro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Product')),
            ],
            options={
                'db_table': 'at_api_test',
            },
        ),
        migrations.AlterField(
            model_name='apis',
            name='api_method',
            field=models.CharField(choices=[('0', 'get'), ('1', 'post')], default='get', max_length=200),
        ),
        migrations.AddField(
            model_name='apistep',
            name='api_test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Apitest'),
        ),
    ]
