# Generated by Django 2.1.3 on 2019-11-26 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20191125_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apitest',
            name='api_t_ter',
            field=models.CharField(max_length=200),
        ),
    ]
