# Generated by Django 2.1.3 on 2019-11-26 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20191126_1116'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apitest',
            old_name='api_t_ter',
            new_name='api_ter',
        ),
    ]
