# Generated by Django 2.1.3 on 2019-11-27 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20191126_1120'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bug_name', models.CharField(max_length=100)),
                ('bug_detail', models.CharField(max_length=500)),
                ('bug_status', models.CharField(choices=[('激活', '激活'), ('已解决', '已解决'), ('已关闭', '已关闭')], default='激活', max_length=200)),
                ('bug_level', models.CharField(choices=[('轻微', '轻微'), ('一般', '一般'), ('严重', '严重')], default='严重', max_length=200)),
                ('bug_creat_er', models.CharField(max_length=200)),
                ('bug_assign', models.CharField(max_length=200)),
                ('create_time', models.DateTimeField(auto_now=True)),
                ('bug_pro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Product')),
            ],
            options={
                'db_table': 'at_bug',
            },
        ),
    ]
