# Generated by Django 2.1.3 on 2019-12-05 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_bug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Set',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_name', models.CharField(max_length=200)),
                ('set_value', models.CharField(max_length=600)),
            ],
            options={
                'db_table': 'at_set',
            },
        ),
    ]
