# Generated by Django 2.1.3 on 2019-12-06 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_set'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apptest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_t_name', models.CharField(max_length=64)),
                ('app_t_desc', models.CharField(max_length=200)),
                ('app_ter', models.CharField(max_length=64)),
                ('app_t_res', models.BooleanField()),
                ('create_time', models.DateTimeField(auto_now=True)),
                ('app_t_pro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Product')),
            ],
            options={
                'db_table': 'at_app_test',
            },
        ),
    ]
