# Generated by Django 2.1.3 on 2019-12-09 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_apptest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appteststep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_step', models.CharField(max_length=200)),
                ('app_find_method', models.CharField(max_length=200)),
                ('app_element', models.CharField(max_length=200)),
                ('app_opt_method', models.CharField(max_length=200)),
                ('app_test_data', models.CharField(max_length=200, null=True)),
                ('app_assert_data', models.CharField(max_length=200)),
                ('app_result', models.BooleanField()),
                ('create_time', models.DateTimeField(auto_now=True)),
                ('app_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Apptest')),
            ],
            options={
                'db_table': 'at_app_step',
            },
        ),
    ]
