# Generated by Django 2.1.3 on 2019-12-09 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_webtest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Webteststep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('web_step', models.CharField(max_length=200)),
                ('web_find_method', models.CharField(max_length=200)),
                ('web_element', models.CharField(max_length=200)),
                ('web_opt_method', models.CharField(max_length=200)),
                ('web_test_data', models.CharField(max_length=200, null=True)),
                ('web_assert_data', models.CharField(max_length=200)),
                ('web_result', models.BooleanField()),
                ('create_time', models.DateTimeField(auto_now=True)),
                ('web_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Webtest')),
            ],
            options={
                'db_table': 'at_web_step',
            },
        ),
    ]
